dist: trusty
os: linux
language: clojure
notifications:
  email:
    - antonin@hildebrand.cz
cache:
  directories:
    - "$HOME/.m2"
    # this is mainly for puppeteer, by default it stores chromium downloads in node_modules/puppeteer/.local-chromium
    - "$HOME/build/binaryage/cljs-devtools/test/node_modules"
before_install:
  - npm i -g npm
  - yes y | sudo lein upgrade
  - curl -sSL https://raw.githubusercontent.com/cljs-oss/canary/master/scripts/install-canary.sh | bash
  - (cd test && npm install)
